config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  resources :sessions, only: [:create, :destroy]
  
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/debug'
  
  post 'index/add'
  get 'index/recent'
  get 'index/time'
  get 'index/name'
  get 'index/index/:id', to: 'index#index', as: 'edit'
  
  get 'index/settings'
  
  delete 'index/destroy'
  post 'index/edit'
  post 'index/change'
  post 'index/makerequest'
  delete 'index/deleteRequest'
  
  get 'index/show'
  get 'index/index'
  
  
  root 'index#show'

end

app/models/event.rb
class Event < ActiveRecord::Base
    has_and_belongs_to_many :users
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :events
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.first_name = auth.info.name.split(' ')[0]
      user.last_name = auth.info.name.split(' ')[1]
      user.image = auth.info.image
      user.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end
  
  def index
    @events = Event.paginate(:page => params[:page]).order('created_at DESC')
    @myevents = Event.where(authorID: current_user.uid).paginate(:page => params[:page]).order('created_at DESC')
    @requests = current_user.events.paginate(:page => params[:page]).order('created_at DESC')
  end
  
  def add
    name = params[:name]
    location = params[:location]
    time = params[:time]
    datetime = params[:date]+ " " + params[:time]

    Event.create!(
      title: name, 
      location: location,
      time: time,
      authorID: current_user.uid,
      datetime: datetime
    )
    flash[:notice] = "Event successfully posted!"
    redirect_to "/index/index"
  end

  def destroy
    Event.find(params[:id]).delete
    redirect_to '/index/index'
  end
  
  def edit
    @eventedit = Event.find(params[:id])
    puts @eventedit.title
    redirect_to edit_path(:id => params[:id], :anchor => 'editEvents')
    #render :text => @eventedit.title
  end
  
  def change
    name = params[:name]
    location = params[:location]
    time = params[:time]
    eid = params[:eid]
    Event.update(
      eid,
      title: name, 
      location: location,
      time: time
    )
    redirect_to '/index/index'
  end
  
  def makerequest
    Event.find(params[:id]).users.push(current_user)
    
    #flash[:notice] = "Request successfully sent!"
    redirect_to "/index/index"
  end
  
  def deleteRequest
    Event.find(params[:id]).users.delete(current_user)
    
    redirect_to '/index/index'
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to "/index/index"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
  def user_params
    params.require(:user).permit(:provider, :uid, :name, :first_name, :last_name, :image, :oauth_token, :oauth_expires_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/events/_event.html.erb
<div class="event">
  <div class="container-fluid">
    <div class="thumbnail">
      <div class='row'>
        <img class='col-md-2' src=<%="https://graph.facebook.com/" + event.authorID + "/picture?type=large"%> class="post-image">
        <div class='col-md-10'>
          <h3><%= "Who's down for " + event.title %></h3>
          <br>
          <br>
          <div class='row'>
            <div class='col-md-4'>
              <h3><%= "Time: " +  event.datetime.to_s()%></h3>
            </div>
            <div class='col-md-6'>
              <h3><%= " Location: " + event.location %></h3>
            </div>
          </div>

        </div>
      </div>
      <% if event.authorID == current_user.uid %>
        <%= link_to 'Delete', {action: "destroy", id: event.id}, {:class => 'btn btn-danger event-btn', method: 'DELETE'} %>
        <%= link_to 'Edit', {action: "edit", id: event.id}, {:class => 'btn btn-info event-btn', method: 'POST'} %>

      <% elsif current_user.events.where(id: event.id).exists?%>
        <%= form_tag({controller: "index", action: "deleteRequest", id: event.id}, method: "delete") do %>
              <div class="form-group">
                        <button class="btn btn-primary event-btn">I'm Down <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button>
              </div>
        <% end %>
      <% else %>
        <%= form_tag({controller: "index", action: "makerequest", id: event.id}, method: "post") do %>
              <div class="form-group">
                        <button class="btn btn-primary event-btn">I'm Down</button>
              </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/index/_inputform.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <!--<form class="form-horizontal" action="" method="post">
                          <fieldset>-->
            <% if params[:id] %>
                <%- @action = 'change' %>
            <% else %>
                <%- @action = 'add'%>
            <% end %>
            
            <%=form_tag({controller: "index", action: @action}, method: "post") do %>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="name">What:</label>
                    <div class="col-md-9">
                        <input id="name" name="name" type="text" placeholder=<%= params[:id] ? Event.find(params[:id]).title : 'What...' %> class="form-control">
                    </div>
                </div>

                <div class="col-xs-12" style="height:25px;"></div>

                <div class="form-group">
                    <label class="col-md-3 control-label" for="email">Where:</label>
                    <div class="col-md-9">
                        <input id="location" name="location" type="text" placeholder=<%= params[:id] ? Event.find(params[:id]).location : 'Where...' %> class="form-control">
                    </div>
                </div>

                <div class="col-xs-12" style="height:25px;"></div>

                <div class="form-group">
                    <label class="col-md-3 control-label" for="message">When:</label>
                    <div class="col-md-9">
                        <input id="time" name="time" type="time" placeholder=<%= params[:id] ? Event.find(params[:id]).time : 'When...' %> class="form-control">
                    </div>
                </div>

                <div class="col-xs-12" style="height:25px;"></div>


                <div class="form-group">
                    <label class="col-md-3 control-label" for="message">Date:</label>
                    <div class="col-md-9">
                        <input id="date" name="date" type="date" placeholder=<%= params[:id] ? Event.find(params[:id]).datetime : 'What...' %> class="form-control">
                    </div>
                </div>



                <!--Doesn't work-->
                <!--<div style="overflow:hidden;">-->
                <!--    <div class="form-group">-->
                <!--        <div class="row">-->
                <!--            <div class="col-md-8">-->
                <!--                <div id="datetimepicker1"></div>-->
                <!--            </div>-->
                <!--        </div>-->
                <!--    </div>-->
                <!--    <script type="text/javascript">-->
                <!--        $(function () {-->
                <!--            $('#datetimepicker1').datepicker({-->
                <!--                inline: true,-->
                <!--                sideBySide: true-->
                <!--            });-->
                <!--        });-->
                <!--    </script>-->
                <!--</div>-->

                <input id="eid" name="eid" type="hidden" value=<%= params[:id] %> />

                <div class="col-xs-12" style="height:25px;"></div>

                <div class="form-group">
                    <div id="submitButtonDiv" class="col-md-12 text-center">

                    <% if params[:id] %>
                        <button class="btn btn-primary btn-lg">Edit</button>
                    <% else %>
                        <button class="btn btn-primary btn-lg">Submit</button>
                    <% end %>
            
                        
                    </div>
                </div>


                <% end %>
                    <!--</fieldset>
                          </form>-->
        </div>
    </div>
</div>

app/views/index/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Bootstrap, CSS, and stylesheet-->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="RUDownTeam">
  <title>RUDown</title>
  <%- stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
    <%- stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/cyborg/bootstrap.min.css" %>
      <%=stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/yeti/bootstrap.min.css" %>
        <%=stylesheet_link_tag "style" %>
</head>

<body>
<div class="container">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" data-toggle="tab" href="#home">RUDown</a>
        </div>
        <div>
          <ul class="nav navbar-nav">
            <li class="active tab">
              <a data-toggle="tab" href="#home" class="">Home</a>
            </li>
            <li class="tab">
              <a id="createEventLink" data-toggle="tab" href="#createEvents" class="">Create Event</a>
            </li>
            <li class="tab">
              <a data-toggle="tab" href="#myRequests" class="">My Requests</a>
            </li>
            <li class="tab">
              <a data-toggle="tab" href="#myEvents" class="">My Events</a>
            </li>
            <li class="tab">
              <a data-toggle="tab" href="#editEvents" class="" id='edit-tab'>Edit Events</a>
            </li>
          </ul>
          
           <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <div class="btn-group show-on-hover pull-right">
                <div class="well well-sm pull-right dropdown-toggle">
                  <a class="pull-right" href="#">
                    <h5 class="pull-right"> <%= current_user.name %> </h5>
                    <img class="media-object profile-name img-circle" src= <%="https://graph.facebook.com/" + current_user.uid + "/picture?type=small" %> >
                  </a>
                </div>
                <ul class="dropdown-menu" role="menu" id="settings-dropdown">
                  <li><a href="settings/">Settings</a></li>
                  <li class="divider"></li>
                  <li>
                    <%=link_to "Sign out", signout_path, id: "sign_out" %>
                  </li>
                </ul>
              </div>
              <% end %>
          </ul>
          
        </div>
      </div>
    </nav>
    <div class="tab-content">
      <div id="home" class="tab-pane fadeIn active">
        <a name="home"></a>
        <h3>Events going on:</h3>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Sort by
            <span class="caret"></span>
          </button>
         
        </div>
        <a id="refresh" href="/" class="btn btn-default"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></a>
        <% if flash[:notice] %>
          <div class="notice">
            <span id="flash"><%= flash[:notice] %></span>
          </div>
          <% end %>
            <br></br>
            <div id="events">
              <%=render @events %>
            </div>
            <%=will_paginate @events %>
      </div>
      
      <div id="createEvents" class="tab-pane fade">
        <a name="createEvents"></a>
        <h3>Create Event</h3>
        <p>Enter new event information here:</p>
          <div>
          <%=render partial: 'inputform', locals: {eventedit: nil} %>
        </div>
      </div>
      
      <div id="myRequests" class="tab-pane fade">
       <h3>My Requests</h3>
        <div id="requests">
          <%=render @requests %>
        </div>
        <%=will_paginate @requests %>
      </div>
      
      <div id="myEvents" class="tab-pane fade">
        <h3>My Events</h3>
        <div id="myevents">
          <%=render @myevents %>
        </div>
        <%=will_paginate @myevents %>
      </div>
      
      <div id="editEvents" class='tab-pane fade'>
        <a name="editEvents"></a>
        <h3>Edit Event</h3>
        <p>Enter new event information here:</p>
        <div>
          <%=render partial: 'inputform', locals: {eventedit: @eventedit} %>
        </div>
      </div>
    </div>
  </div>
</body>
 <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="https://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  <script>
    $(function() {
      var hash = window.location.hash;
      hash && $('ul.nav a[href="' + hash + '"]').tab('show');
    });

    $('.notice').hide().delay(800).fadeIn(800).delay(2000).fadeOut(800)
    
    $('#edit-tab').hide()
  </script>
</html>

app/views/index/index.js.erb
$('#events').append('<%= escape_javascript render(@events) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@events) %>')

$('#myevents').append('<%= escape_javascript render(@myevents) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@myevents) %>')

app/views/index/settings.html.erb
<!DOCTYPE html>
<html lang = "en">
<head>
  <!-- Bootstrap, CSS, and stylesheet-->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="RUDownTeam">
  <title>RUDown - Settings</title>
    <%- stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>

    <!-- Bootswatch Themes http://www.bootstrapcdn.com/bootswatch -->
    <!-- Cyborg -->
    <%- stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/cyborg/bootstrap.min.css" %>
      <!-- Yeti-->
      <%=stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/yeti/bootstrap.min.css" %>

        <!-- Custom styles -->
        <%=stylesheet_link_tag "style" %>
</head>
<body>
<div class ="container">
      <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" data-toggle="tab" href="/home/index">RUDown</a>
        </div>
        <div>
          <ul class="nav navbar-nav">
            <li class="active tab">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <div class="btn-group show-on-hover pull-right">
                <div class="well well-sm pull-right dropdown-toggle">
                  <a class="pull-right" href="#">
                    <h5 class="pull-right"> <%= current_user.name %> </h5>
                    <img class="media-object profile-name img-circle" src= <%="https://graph.facebook.com/" + current_user.uid + "/picture?type=small" %> >
                  </a>
                </div>
                <ul class="dropdown-menu" role="menu" id="settings-dropdown">
                  <li><a href="/index/index">Home</a></li>
                  <li class="divider"></li>
                  <li>
                    <%=link_to "Sign out", signout_path, id: "sign_out" %>
                  </li>
                </ul>
              </div>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>
</div>
</body>
</html>

app/views/index/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook Auth Example</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <%= stylesheet_link_tag  "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/yeti/bootstrap.min.css" %>
</head>
<body>
<div>
  <% if current_user %>
    <script type="text/javascript">
        window.location.href="/index/index"  
    </script>
  <% else %>
  <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>R U Down</h1>
                        <hr class="intro-divider">
                            <%= link_to '<i class="fa fa-facebook-official"></i>Sign in with Facebook'.html_safe, "/auth/facebook", id: "sign_in", class: "btn btn-primary btn-large"%>
                    </div>
                </div>
            </div>

        </div>
    </div>
  <% end %>
</div>
<%= yield %>




<div class="container" style="visibility: hidden">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" data-toggle="tab" href="#home">RUDown</a>
        </div>
        <div>
          <ul class="nav navbar-nav">
            <li class="active tab">
              <a data-toggle="tab" href="#home" class="">Home</a>
            </li>
            <li class="tab">
              <a id="createEventLink" data-toggle="tab" href="#createEvents" class="">Create Event</a>
            </li>
            <li class="tab">
              <a data-toggle="tab" href="#myRequests" class="">My Requests</a>
            </li>
            <li class="tab">
              <a data-toggle="tab" href="#myEvents" class="">My Events</a>
            </li>
            <li class="tab">
              <a data-toggle="tab" href="#editEvents" class="" id='edit-tab'>Edit Events</a>
            </li>
          </ul>
          
           <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <div class="btn-group show-on-hover pull-right">
                <div class="well well-sm pull-right dropdown-toggle">
                  <a class="pull-right" href="#">
                    <h5 class="pull-right"> <%= current_user.name %> </h5>
                    <img class="media-object profile-name img-circle" src= <%="https://graph.facebook.com/" + current_user.uid + "/picture?type=small" %> >
                  </a>
                </div>
                <ul class="dropdown-menu" role="menu" id="settings-dropdown">
                  <li><a href="settings/">Settings</a></li>
                  <li class="divider"></li>
                  <li>
                    <%=link_to "Sign out", signout_path, id: "sign_out" %>
                  </li>
                </ul>
              </div>
              <% end %>
          </ul>
          
        </div>
      </div>
    </nav>
    <div class="tab-content">
      <div id="home" class="tab-pane fadeIn active">
        <a name="home"></a>
        <h3>Events going on:</h3>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Sort by
            <span class="caret"></span>
          </button>
         
        </div>
        <a id="refresh" href="/" class="btn btn-default"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></a>
        <% if flash[:notice] %>
          <div class="notice">
            <span id="flash"><%= flash[:notice] %></span>
          </div>
          <% end %>
            <br></br>
            <div id="events">
            </div>
      </div>
      
      <div id="createEvents" class="tab-pane fade">
        <a name="createEvents"></a>
        <h3>Create Event</h3>
        <p>Enter new event information here:</p>
          <div>
        </div>
      </div>
      
      <div id="myRequests" class="tab-pane fade">
       <h3>My Requests</h3>
        <div id="requests">
        </div>
      </div>
      
      <div id="myEvents" class="tab-pane fade">
        <h3>My Events</h3>
        <div id="myevents">
        </div>
      </div>
      
      <div id="editEvents" class='tab-pane fade'>
        <a name="editEvents"></a>
        <h3>Edit Event</h3>
        <p>Enter new event information here:</p>
        <div>
        </div>
      </div>
    </div>
  </div>
  
  
  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RUDown</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reqs/_req.html.erb
<div class="request">
  <div class="container-fluid">
    <div class="thumbnail">
      <div class='row'>
        <img class='col-md-2' src=<%= "https://graph.facebook.com/" + req.requestID + "/picture?type=large"%> class="post-image">
      </div>
    </div>
  </div>
</div>